
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: 'lightblue', height: '64px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
          <p>Header</p>
        </header>
        <main className="pt-16 pb-16">{children}</main>
        <footer style={{ backgroundColor: 'lightblue', height: '64px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  )
}
